<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;

use \test\BREVO\Utils\SpeakeasyMetadata;
class DeleteWebhookRequest
{
    /**
     * Id of the webhook
     * 
     * @var int $webhookId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=webhookId')]
    public int $webhookId;
    
	public function __construct()
	{
		$this->webhookId = 0;
	}
}
