<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;

use \test\BREVO\Utils\SpeakeasyMetadata;
class GetAggregatedSmtpReportRequest
{
    /**
     * Number of days in the past including today (positive integer). _Not compatible with 'startDate' and 'endDate'_
     * 
     * 
     * 
     * @var ?int $days
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=days')]
    public ?int $days = null;
    
    /**
     * **Mandatory if startDate is used.** Ending date of the report (YYYY-MM-DD). Must be greater than equal to startDate
     * 
     * 
     * 
     * @var ?string $endDate
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=endDate')]
    public ?string $endDate = null;
    
    /**
     * **Mandatory if endDate is used.** Starting date of the report (YYYY-MM-DD). Must be lower than equal to endDate
     * 
     * 
     * 
     * @var ?string $startDate
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=startDate')]
    public ?string $startDate = null;
    
    /**
     * Tag of the emails
     * 
     * @var ?string $tag
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=tag')]
    public ?string $tag = null;
    
	public function __construct()
	{
		$this->days = null;
		$this->endDate = null;
		$this->startDate = null;
		$this->tag = null;
	}
}
