<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;


class GetCrmPipelineDetailsResponse
{
	
    public string $contentType;
    
    /**
     * Returns list of pipeline stages
     * 
     * @var ?\test\BREVO\Models\Shared\Pipeline $pipeline
     */
	
    public ?\test\BREVO\Models\Shared\Pipeline $pipeline = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->pipeline = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
