<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;


class GetCrmFilesIdResponse
{
	
    public string $contentType;
    
    /**
     * Returns downloadable file link. Valid for next 5 minutes only.
     * 
     * @var ?\test\BREVO\Models\Shared\FileDownloadableLink $fileDownloadableLink
     */
	
    public ?\test\BREVO\Models\Shared\FileDownloadableLink $fileDownloadableLink = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Returned when invalid data posted
     * 
     * @var ?\test\BREVO\Models\Shared\ErrorModel $errorModel
     */
	
    public ?\test\BREVO\Models\Shared\ErrorModel $errorModel = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->fileDownloadableLink = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->errorModel = null;
	}
}
