<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;


class GetCrmTasktypesResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Returns all the Task types
     * 
     * @var ?\test\BREVO\Models\Shared\TaskTypes $taskTypes
     */
	
    public ?\test\BREVO\Models\Shared\TaskTypes $taskTypes = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->taskTypes = null;
	}
}
