<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;


class GetCrmFilesIdDataResponse
{
	
    public string $contentType;
    
    /**
     * Returned when file is found.
     * 
     * @var ?\test\BREVO\Models\Shared\FileData $fileData
     */
	
    public ?\test\BREVO\Models\Shared\FileData $fileData = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Returned when invalid data posted
     * 
     * @var ?\test\BREVO\Models\Shared\ErrorModel $errorModel
     */
	
    public ?\test\BREVO\Models\Shared\ErrorModel $errorModel = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->fileData = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->errorModel = null;
	}
}
