<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;


/** Filter on the type of statistics required. Example **globalStats** value will only fetch globalStats info of the campaign in returned response. */
enum GetEmailCampaignsStatistics: string
{
    case GlobalStats = 'globalStats';
    case LinksStats = 'linksStats';
    case StatsByDomain = 'statsByDomain';
}
