<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;

use \test\BREVO\Utils\SpeakeasyMetadata;
class GetInboundEmailAttachmentRequest
{
    /**
     * Token to fetch a particular attachment
     * 
     * @var string $downloadToken
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=downloadToken')]
    public string $downloadToken;
    
	public function __construct()
	{
		$this->downloadToken = "";
	}
}
