<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;


/** Filter the report for specific events */
enum GetSmsEventsEvent: string
{
    case Bounces = 'bounces';
    case HardBounces = 'hardBounces';
    case SoftBounces = 'softBounces';
    case Delivered = 'delivered';
    case Sent = 'sent';
    case Accepted = 'accepted';
    case Unsubscription = 'unsubscription';
    case Replies = 'replies';
    case Blocked = 'blocked';
    case Rejected = 'rejected';
}
