<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;


/** Filter on webhook type */
enum GetWebhooksType: string
{
    case Marketing = 'marketing';
    case Transactional = 'transactional';
    case Inbound = 'inbound';
}
