<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;


/** Filter the report for a specific event type */
enum GetWhatsappEventReportEvent: string
{
    case Sent = 'sent';
    case Delivered = 'delivered';
    case Read = 'read';
    case Error = 'error';
    case Unsubscribe = 'unsubscribe';
    case Reply = 'reply';
    case SoftBounce = 'soft-bounce';
}
