<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;

use \test\BREVO\Utils\SpeakeasyMetadata;
class GetWhatsappEventReportRequest
{
    /**
     * Filter results for specific contact (WhatsApp Number with country code. Example, 85264318721)
     * 
     * @var ?string $contactNumber
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=contactNumber')]
    public ?string $contactNumber = null;
    
    /**
     * Number of days in the past including today (positive integer). _Not compatible with 'startDate' and 'endDate'_
     * 
     * 
     * 
     * @var ?int $days
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=days')]
    public ?int $days = null;
    
    /**
     * **Mandatory if startDate is used.** Ending date of the report (YYYY-MM-DD). Must be greater than equal to startDate
     * 
     * 
     * 
     * @var ?string $endDate
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=endDate')]
    public ?string $endDate = null;
    
    /**
     * Filter the report for a specific event type
     * 
     * @var ?\test\BREVO\Models\Operations\QueryParamEvent $event
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=event')]
    public ?QueryParamEvent $event = null;
    
    /**
     * Number limitation for the result returned
     * 
     * @var ?int $limit
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;
    
    /**
     * Beginning point in the list to retrieve from
     * 
     * @var ?int $offset
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=offset')]
    public ?int $offset = null;
    
    /**
     * Sort the results in the ascending/descending order of record creation. Default order is **descending** if `sort` is not passed
     * 
     * @var ?\test\BREVO\Models\Operations\GetWhatsappEventReportQueryParamSort $sort
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=sort')]
    public ?GetWhatsappEventReportQueryParamSort $sort = null;
    
    /**
     * **Mandatory if endDate is used.** Starting date of the report (YYYY-MM-DD). Must be lower than equal to endDate
     * 
     * 
     * 
     * @var ?string $startDate
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=startDate')]
    public ?string $startDate = null;
    
	public function __construct()
	{
		$this->contactNumber = null;
		$this->days = null;
		$this->endDate = null;
		$this->event = null;
		$this->limit = null;
		$this->offset = null;
		$this->sort = null;
		$this->startDate = null;
	}
}
