<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;


/**
 * PatchCrmDealsLinkUnlinkIdRequestBody - Linked / Unlinked contacts and companies ids.
 * 
 * @package test\BREVO\Models\Operations
 * @access public
 */
class PatchCrmDealsLinkUnlinkIdRequestBody
{
    /**
     * Company ids to be linked with deal
     * 
     * @var ?array<string> $linkCompanyIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('linkCompanyIds')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $linkCompanyIds = null;
    
    /**
     * Contact ids for contacts to be linked with deal
     * 
     * @var ?array<int> $linkContactIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('linkContactIds')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $linkContactIds = null;
    
    /**
     * Company ids to be unlinked from deal
     * 
     * @var ?array<string> $unlinkCompanyIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('unlinkCompanyIds')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $unlinkCompanyIds = null;
    
    /**
     * Contact ids for contacts to be unlinked from deal
     * 
     * @var ?array<int> $unlinkContactIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('unlinkContactIds')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $unlinkContactIds = null;
    
	public function __construct()
	{
		$this->linkCompanyIds = null;
		$this->linkContactIds = null;
		$this->unlinkCompanyIds = null;
		$this->unlinkContactIds = null;
	}
}
