<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;


/**
 * PatchCompaniesLinkUnlinkIdRequestBody - Linked / Unlinked contacts and deals ids.
 * 
 * @package test\BREVO\Models\Operations
 * @access public
 */
class PatchCompaniesLinkUnlinkIdRequestBody
{
    /**
     * Contact ids for contacts to be linked with company
     * 
     * @var ?array<int> $linkContactIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('linkContactIds')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $linkContactIds = null;
    
    /**
     * Deal ids for deals to be linked with company
     * 
     * @var ?array<string> $linkDealsIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('linkDealsIds')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $linkDealsIds = null;
    
    /**
     * Contact ids for contacts to be unlinked from company
     * 
     * @var ?array<int> $unlinkContactIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('unlinkContactIds')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $unlinkContactIds = null;
    
    /**
     * Deal ids for deals to be unlinked from company
     * 
     * @var ?array<string> $unlinkDealsIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('unlinkDealsIds')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $unlinkDealsIds = null;
    
	public function __construct()
	{
		$this->linkContactIds = null;
		$this->linkDealsIds = null;
		$this->unlinkContactIds = null;
		$this->unlinkDealsIds = null;
	}
}
