<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;


/**
 * PatchCrmDealsIdAttributes - Attributes for deal update
 * 
 * 
 * If you wish to update the pipeline of a deal you need to provide the `pipeline` and the `deal_stage`
 * 
 * Pipeline and deal_stage are ids you can fetch using this endpoint `/crm/pipeline/details/{pipelineID}`
 * 
 * 
 * @package test\BREVO\Models\Operations
 * @access public
 */
class PatchCrmDealsIdAttributes
{
	public function __construct()
	{
	}
}
