<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;


/**
 * PatchCompaniesIdRequestBodyAttributes - Attributes for company update
 * 
 * @package test\BREVO\Models\Operations
 * @access public
 */
class PatchCompaniesIdRequestBodyAttributes
{
	public function __construct()
	{
	}
}
