<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;

use \test\BREVO\Utils\SpeakeasyMetadata;
class PatchCrmTasksIdRequest
{
    /**
     * Updated task details.
     * 
     * @var \test\BREVO\Models\Operations\PatchCrmTasksIdRequestBody $requestBody
     */
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public PatchCrmTasksIdRequestBody $requestBody;
    
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;
    
	public function __construct()
	{
		$this->requestBody = new \test\BREVO\Models\Operations\PatchCrmTasksIdRequestBody();
		$this->id = "";
	}
}
