<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;


class PostConversationsPushedMessagesRequestBody
{
    /**
     * agent ID. It can be found on agent’s page or received <a href="https://developers.brevo.com/docs/conversations-webhooks">from a webhook</a>.
     * 
     * @var mixed $agentId
     */
	#[\JMS\Serializer\Annotation\SerializedName('agentId')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public mixed $agentId = null;
    
    /**
     * group ID. It can be found on group’s page.
     * 
     * @var mixed $groupId
     */
	#[\JMS\Serializer\Annotation\SerializedName('groupId')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public mixed $groupId = null;
    
    /**
     * message text
     * 
     * @var mixed $text
     */
	#[\JMS\Serializer\Annotation\SerializedName('text')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $text;
    
    /**
     * visitor’s ID received <a href="https://developers.brevo.com/docs/conversations-webhooks">from a webhook</a> or generated by you to <a href="https://developers.brevo.com/docs/customize-the-widget#identifying-existing-users">bind existing user account to Conversations</a>
     * 
     * @var mixed $visitorId
     */
	#[\JMS\Serializer\Annotation\SerializedName('visitorId')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $visitorId;
    
	public function __construct()
	{
		$this->agentId = null;
		$this->groupId = null;
		$this->text = null;
		$this->visitorId = null;
	}
}
