<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;

use \test\BREVO\Utils\SpeakeasyMetadata;
class PutCorporateSubAccountIdPlanRequest
{
    /**
     * Id of the sub-account organization
     * 
     * @var int $id
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public int $id;
    
    /**
     * Values to update a sub-account plan
     * 
     * @var \test\BREVO\Models\Shared\SubAccountUpdatePlanRequest $subAccountUpdatePlanRequest
     */
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \test\BREVO\Models\Shared\SubAccountUpdatePlanRequest $subAccountUpdatePlanRequest;
    
	public function __construct()
	{
		$this->id = 0;
		$this->subAccountUpdatePlanRequest = new \test\BREVO\Models\Shared\SubAccountUpdatePlanRequest();
	}
}
