<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;


class SendTestEmailResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Test email could not be sent to the following email addresses
     * 
     * @var ?\test\BREVO\Models\Shared\PostSendFailed $postSendFailed
     */
	
    public ?\test\BREVO\Models\Shared\PostSendFailed $postSendFailed = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->postSendFailed = null;
	}
}
