<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;

use \test\BREVO\Utils\SpeakeasyMetadata;
class SendSmsReportRequest
{
    /**
     * id of the campaign
     * 
     * @var int $campaignId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=campaignId')]
    public int $campaignId;
    
    /**
     * Values for send a report
     * 
     * @var \test\BREVO\Models\Shared\SendReport $sendReport
     */
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \test\BREVO\Models\Shared\SendReport $sendReport;
    
	public function __construct()
	{
		$this->campaignId = 0;
		$this->sendReport = new \test\BREVO\Models\Shared\SendReport();
	}
}
