<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;

use \test\BREVO\Utils\SpeakeasyMetadata;
class SendTestSmsRequest
{
    /**
     * Id of the SMS campaign
     * 
     * @var int $campaignId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=campaignId')]
    public int $campaignId;
    
    /**
     * Mobile number of the recipient with the country code. This number **must belong to one of your contacts in Brevo account and must not be blacklisted**
     * 
     * 
     * 
     * @var \test\BREVO\Models\Shared\SendTestSms $sendTestSms
     */
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \test\BREVO\Models\Shared\SendTestSms $sendTestSms;
    
	public function __construct()
	{
		$this->campaignId = 0;
		$this->sendTestSms = new \test\BREVO\Models\Shared\SendTestSms();
	}
}
