<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;


class SendTestSmsResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Campaign ID not found
     * 
     * @var ?\test\BREVO\Models\Shared\ErrorModel $errorModel
     */
	
    public ?\test\BREVO\Models\Shared\ErrorModel $errorModel = null;
    
    /**
     * Test SMS could not be sent to the following email addresses
     * 
     * @var ?\test\BREVO\Models\Shared\PostSendSmsTestFailed $postSendSmsTestFailed
     */
	
    public ?\test\BREVO\Models\Shared\PostSendSmsTestFailed $postSendSmsTestFailed = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->errorModel = null;
		$this->postSendSmsTestFailed = null;
	}
}
