<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;

use \test\BREVO\Utils\SpeakeasyMetadata;
class UpdateChildDomainRequest
{
    /**
     * Either auth key or id of reseller's child
     * 
     * @var string $childIdentifier
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=childIdentifier')]
    public string $childIdentifier;
    
    /**
     * Pass the existing domain that needs to be updated
     * 
     * @var string $domainName
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=domainName')]
    public string $domainName;
    
    /**
     * value to update for sender domain
     * 
     * @var \test\BREVO\Models\Shared\UpdateChildDomain $updateChildDomain
     */
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \test\BREVO\Models\Shared\UpdateChildDomain $updateChildDomain;
    
	public function __construct()
	{
		$this->childIdentifier = "";
		$this->domainName = "";
		$this->updateChildDomain = new \test\BREVO\Models\Shared\UpdateChildDomain();
	}
}
