<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;


/**
 * UpdateCouponCollectionRequestBody - Values to update the coupon collection
 * 
 * @package test\BREVO\Models\Operations
 * @access public
 */
class UpdateCouponCollectionRequestBody
{
    /**
     * A default coupon to be used in case there are no coupons left
     * 
     * @var string $defaultCoupon
     */
	#[\JMS\Serializer\Annotation\SerializedName('defaultCoupon')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $defaultCoupon;
    
	public function __construct()
	{
		$this->defaultCoupon = "";
	}
}
