<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;

use \test\BREVO\Utils\SpeakeasyMetadata;
class UpdateExternalFeedRequest
{
    /**
     * Values to update a feed
     * 
     * @var \test\BREVO\Models\Shared\UpdateExternalFeed $updateExternalFeed
     */
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \test\BREVO\Models\Shared\UpdateExternalFeed $updateExternalFeed;
    
    /**
     * UUID of the feed to update
     * 
     * @var string $uuid
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=uuid')]
    public string $uuid;
    
	public function __construct()
	{
		$this->updateExternalFeed = new \test\BREVO\Models\Shared\UpdateExternalFeed();
		$this->uuid = "";
	}
}
