<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;

use \test\BREVO\Utils\SpeakeasyMetadata;
class UpdateContactRequest
{
    /**
     * Email (urlencoded) OR ID of the contact
     * 
     * @var mixed $identifier
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=identifier')]
    public mixed $identifier;
    
    /**
     * Values to update a contact
     * 
     * @var \test\BREVO\Models\Shared\UpdateContact $updateContact
     */
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \test\BREVO\Models\Shared\UpdateContact $updateContact;
    
	public function __construct()
	{
		$this->identifier = null;
		$this->updateContact = new \test\BREVO\Models\Shared\UpdateContact();
	}
}
