<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Operations;

use \test\BREVO\Utils\SpeakeasyMetadata;
class ValidateSenderByOTPRequest
{
    /**
     * otp
     * 
     * @var ?\test\BREVO\Models\Shared\Otp $otp
     */
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?\test\BREVO\Models\Shared\Otp $otp = null;
    
    /**
     * Id of the sender
     * 
     * @var int $senderId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=senderId')]
    public int $senderId;
    
	public function __construct()
	{
		$this->otp = null;
		$this->senderId = 0;
	}
}
