<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * AddChildDomain - Sender domain to add for a specific child account. This will not be displayed to the parent account.
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class AddChildDomain
{
    /**
     * Sender domain to add for a specific child account
     * 
     * @var ?string $domain
     */
	#[\JMS\Serializer\Annotation\SerializedName('domain')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $domain = null;
    
	public function __construct()
	{
		$this->domain = null;
	}
}
