<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class CreateSender
{
    /**
     * From email to use for the sender. A verification email will be sent to this address.
     * 
     * @var string $email
     */
	#[\JMS\Serializer\Annotation\SerializedName('email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $email;
    
    /**
     * **Mandatory in case of dedicated IP**. IPs to associate to the sender
     * 
     * 
     * 
     * @var ?array<\test\BREVO\Models\Shared\CreateSenderIps> $ips
     */
	#[\JMS\Serializer\Annotation\SerializedName('ips')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\CreateSenderIps>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $ips = null;
    
    /**
     * From Name to use for the sender
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	public function __construct()
	{
		$this->email = "";
		$this->ips = null;
		$this->name = "";
	}
}
