<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * CreateWhatsAppCampaignRecipients - Segment ids and List ids to include/exclude from campaign
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class CreateWhatsAppCampaignRecipients
{
    /**
     * List ids to exclude from the campaign
     * 
     * @var ?array<int> $excludedListIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('excludedListIds')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $excludedListIds = null;
    
    /**
     * **Mandatory if scheduledAt is not empty**. List Ids to send the campaign to
     * 
     * 
     * 
     * @var ?array<int> $listIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('listIds')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $listIds = null;
    
    /**
     * **Mandatory if listIds are not used**. Segment ids to send the campaign to.
     * 
     * 
     * 
     * @var ?array<int> $segments
     */
	#[\JMS\Serializer\Annotation\SerializedName('segments')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $segments = null;
    
	public function __construct()
	{
		$this->excludedListIds = null;
		$this->listIds = null;
		$this->segments = null;
	}
}
