<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * CreateChild - reseller child to add
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class CreateChild
{
    /**
     * Company name to use to create the child account
     * 
     * @var string $companyName
     */
	#[\JMS\Serializer\Annotation\SerializedName('companyName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $companyName;
    
    /**
     * Email address to create the child account
     * 
     * @var string $email
     */
	#[\JMS\Serializer\Annotation\SerializedName('email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $email;
    
    /**
     * First name to use to create the child account
     * 
     * @var string $firstName
     */
	#[\JMS\Serializer\Annotation\SerializedName('firstName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $firstName;
    
    /**
     * Language of the child account
     * 
     * @var ?\test\BREVO\Models\Shared\CreateChildLanguage $language
     */
	#[\JMS\Serializer\Annotation\SerializedName('language')]
    #[\JMS\Serializer\Annotation\Type('enum<test\BREVO\Models\Shared\CreateChildLanguage>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreateChildLanguage $language = null;
    
    /**
     * Last name to use to create the child account
     * 
     * @var string $lastName
     */
	#[\JMS\Serializer\Annotation\SerializedName('lastName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $lastName;
    
    /**
     * Password for the child account to login
     * 
     * @var string $password
     */
	#[\JMS\Serializer\Annotation\SerializedName('password')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $password;
    
	public function __construct()
	{
		$this->companyName = "";
		$this->email = "";
		$this->firstName = "";
		$this->language = null;
		$this->lastName = "";
		$this->password = "";
	}
}
