<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * DealsList - List of Deals
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class DealsList
{
    /**
     * List of deals
     * 
     * @var ?array<\test\BREVO\Models\Shared\Deal> $items
     */
	#[\JMS\Serializer\Annotation\SerializedName('items')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\Deal>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $items = null;
    
	public function __construct()
	{
		$this->items = null;
	}
}
