<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * Email - Custom attributes for the report email.
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class Email
{
    /**
     * Custom text message to be presented in the report email.
     * 
     * @var string $body
     */
	#[\JMS\Serializer\Annotation\SerializedName('body')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $body;
    
    /**
     * Email addresses of the recipients
     * 
     * @var array<string> $to
     */
	#[\JMS\Serializer\Annotation\SerializedName('to')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $to;
    
	public function __construct()
	{
		$this->body = "";
		$this->to = [];
	}
}
