<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/** Type of recipients to export for a campaign */
enum EmailExportRecipientsRecipientsType: string
{
    case All = 'all';
    case NonClickers = 'nonClickers';
    case NonOpeners = 'nonOpeners';
    case Clickers = 'clickers';
    case Openers = 'openers';
    case SoftBounces = 'softBounces';
    case HardBounces = 'hardBounces';
    case Unsubscribed = 'unsubscribed';
}
