<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * ErrorModel - bad request
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class ErrorModel
{
    /**
     * Error code displayed in case of a failure
     * 
     * @var \test\BREVO\Models\Shared\ErrorModelCode $code
     */
	#[\JMS\Serializer\Annotation\SerializedName('code')]
    #[\JMS\Serializer\Annotation\Type('enum<test\BREVO\Models\Shared\ErrorModelCode>')]
    public ErrorModelCode $code;
    
    /**
     * Readable message associated to the failure
     * 
     * @var string $message
     */
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $message;
    
	public function __construct()
	{
		$this->code = \test\BREVO\Models\Shared\ErrorModelCode::InvalidParameter;
		$this->message = "";
	}
}
