<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/** Filter the history for a specific event type */
enum ExportWebhooksHistoryEvent: string
{
    case InvalidParameter = 'invalid_parameter';
    case MissingParameter = 'missing_parameter';
    case HardBounce = 'hardBounce';
    case SoftBounce = 'softBounce';
    case Delivered = 'delivered';
    case Spam = 'spam';
    case Request = 'request';
    case Opened = 'opened';
    case Click = 'click';
    case Invalid = 'invalid';
    case Deferred = 'deferred';
    case Blocked = 'blocked';
    case Unsubscribed = 'unsubscribed';
    case Error = 'error';
    case UniqueOpened = 'uniqueOpened';
    case LoadedByProxy = 'loadedByProxy';
    case AllEvents = 'allEvents';
}
