<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * FileData - File data that is uploaded
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class FileData
{
    /**
     * Account id of user which created the file
     * 
     * @var ?string $authorId
     */
	#[\JMS\Serializer\Annotation\SerializedName('authorId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $authorId = null;
    
    /**
     * Company id linked to a file
     * 
     * @var ?string $companyId
     */
	#[\JMS\Serializer\Annotation\SerializedName('companyId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $companyId = null;
    
    /**
     * Contact id of contact on which file is uploaded
     * 
     * @var ?int $contactId
     */
	#[\JMS\Serializer\Annotation\SerializedName('contactId')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $contactId = null;
    
    /**
     * File created date/time
     * 
     * @var ?\DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('createdAt')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $createdAt = null;
    
    /**
     * Deal id linked to a file
     * 
     * @var ?string $dealId
     */
	#[\JMS\Serializer\Annotation\SerializedName('dealId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $dealId = null;
    
    /**
     * Name of uploaded file
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
    /**
     * Size of file in bytes
     * 
     * @var ?int $size
     */
	#[\JMS\Serializer\Annotation\SerializedName('size')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $size = null;
    
	public function __construct()
	{
		$this->authorId = null;
		$this->companyId = null;
		$this->contactId = null;
		$this->createdAt = null;
		$this->dealId = null;
		$this->name = null;
		$this->size = null;
	}
}
