<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * GetAttributes - Attributes listed
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class GetAttributes
{
    /**
     * Listing of available contact attributes in your account
     * 
     * @var array<\test\BREVO\Models\Shared\GetAttributesAttributes> $attributes
     */
	#[\JMS\Serializer\Annotation\SerializedName('attributes')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\GetAttributesAttributes>')]
    public array $attributes;
    
	public function __construct()
	{
		$this->attributes = [];
	}
}
