<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class GetAccountActivity
{
    /**
     * Get user activity logs
     * 
     * @var ?array<\test\BREVO\Models\Shared\Logs> $logs
     */
	#[\JMS\Serializer\Annotation\SerializedName('logs')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\Logs>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $logs = null;
    
	public function __construct()
	{
		$this->logs = null;
	}
}
