<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class GetAccountActivityLogs
{
    /**
     * Type of activity in the account.
     * 
     * @var string $action
     */
	#[\JMS\Serializer\Annotation\SerializedName('action')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $action;
    
    /**
     * Time of the activity.
     * 
     * @var string $date
     */
	#[\JMS\Serializer\Annotation\SerializedName('date')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $date;
    
    /**
     * Browser details of the user who performed the activity.
     * 
     * @var string $userAgent
     */
	#[\JMS\Serializer\Annotation\SerializedName('user_agent')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $userAgent;
    
    /**
     * Email address of the user who performed activity in the account.
     * 
     * @var string $userEmail
     */
	#[\JMS\Serializer\Annotation\SerializedName('user_email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $userEmail;
    
    /**
     * IP address of the user who performed activity in the account.
     * 
     * @var string $userIp
     */
	#[\JMS\Serializer\Annotation\SerializedName('user_ip')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $userIp;
    
	public function __construct()
	{
		$this->action = "";
		$this->date = "";
		$this->userAgent = "";
		$this->userEmail = "";
		$this->userIp = "";
	}
}
