<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class GetCouponCollection
{
    /**
     * Datetime on which the collection was created
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('createdAt')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
    /**
     * The default coupon of the collection
     * 
     * @var string $defaultCoupon
     */
	#[\JMS\Serializer\Annotation\SerializedName('defaultCoupon')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $defaultCoupon;
    
    /**
     * The id of the collection
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The name of the collection
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * Not sent coupons in the collection
     * 
     * @var int $remainingCoupons
     */
	#[\JMS\Serializer\Annotation\SerializedName('remainingCoupons')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $remainingCoupons;
    
    /**
     * Total coupons in the collection
     * 
     * @var int $totalCoupons
     */
	#[\JMS\Serializer\Annotation\SerializedName('totalCoupons')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $totalCoupons;
    
	public function __construct()
	{
		$this->createdAt = new \DateTime();
		$this->defaultCoupon = "";
		$this->id = "";
		$this->name = "";
		$this->remainingCoupons = 0;
		$this->totalCoupons = 0;
	}
}
