<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * GetDomainConfigurationModel - domain configuration
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class GetDomainConfigurationModel
{
    /**
     * Status of domain authentication (true=authenticated, false=non authenticated)
     * 
     * @var bool $authenticated
     */
	#[\JMS\Serializer\Annotation\SerializedName('authenticated')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $authenticated;
    
	#[\JMS\Serializer\Annotation\SerializedName('dns_records')]
    #[\JMS\Serializer\Annotation\Type('test\BREVO\Models\Shared\GetDomainConfigurationModelDnsRecords')]
    public GetDomainConfigurationModelDnsRecords $dnsRecords;
    
    /**
     * Domain
     * 
     * @var string $domain
     */
	#[\JMS\Serializer\Annotation\SerializedName('domain')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $domain;
    
    /**
     * Status of domain verification (true=verified, false=non verified)
     * 
     * @var bool $verified
     */
	#[\JMS\Serializer\Annotation\SerializedName('verified')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $verified;
    
	public function __construct()
	{
		$this->authenticated = false;
		$this->dnsRecords = new \test\BREVO\Models\Shared\GetDomainConfigurationModelDnsRecords();
		$this->domain = "";
		$this->verified = false;
	}
}
