<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * GetDomainsList - list of domains
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class GetDomainsList
{
    /**
     * List of the domains available in your account
     * 
     * @var ?array<\test\BREVO\Models\Shared\GetDomainsListDomains> $domains
     */
	#[\JMS\Serializer\Annotation\SerializedName('domains')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\GetDomainsListDomains>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $domains = null;
    
	public function __construct()
	{
		$this->domains = null;
	}
}
