<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class GetEmailCampaign
{
    /**
     * Status of A/B Test for the campaign. abTesting = false means it is disabled, & abTesting = true means it is enabled.
     * 
     * @var ?bool $abTesting
     */
	#[\JMS\Serializer\Annotation\SerializedName('abTesting')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $abTesting = null;
    
    /**
     * Creation UTC date-time of the campaign (YYYY-MM-DDTHH:mm:ss.SSSZ)
     * 
     * @var string $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('createdAt')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $createdAt;
    
    /**
     * Footer of the campaign
     * 
     * @var string $footer
     */
	#[\JMS\Serializer\Annotation\SerializedName('footer')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $footer;
    
    /**
     * Header of the campaign
     * 
     * @var string $header
     */
	#[\JMS\Serializer\Annotation\SerializedName('header')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $header;
    
    /**
     * HTML content of the campaign
     * 
     * @var string $htmlContent
     */
	#[\JMS\Serializer\Annotation\SerializedName('htmlContent')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $htmlContent;
    
    /**
     * ID of the campaign
     * 
     * @var int $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
    /**
     * Status of inline image. inlineImageActivation = false means image can’t be embedded, & inlineImageActivation = true means image can be embedded, in the email.
     * 
     * @var ?bool $inlineImageActivation
     */
	#[\JMS\Serializer\Annotation\SerializedName('inlineImageActivation')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $inlineImageActivation = null;
    
    /**
     * Status of mirror links in campaign. mirrorActive = false means mirror links are deactivated, & mirrorActive = true means mirror links are activated, in the campaign
     * 
     * @var ?bool $mirrorActive
     */
	#[\JMS\Serializer\Annotation\SerializedName('mirrorActive')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $mirrorActive = null;
    
    /**
     * UTC date-time of last modification of the campaign (YYYY-MM-DDTHH:mm:ss.SSSZ)
     * 
     * @var string $modifiedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('modifiedAt')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $modifiedAt;
    
    /**
     * Name of the campaign
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * Preview text or preheader of the email campaign
     * 
     * @var ?string $previewText
     */
	#[\JMS\Serializer\Annotation\SerializedName('previewText')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $previewText = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('recipients')]
    #[\JMS\Serializer\Annotation\Type('test\BREVO\Models\Shared\GetEmailCampaignRecipients')]
    public GetEmailCampaignRecipients $recipients;
    
    /**
     * FOR TRIGGER ONLY ! Type of trigger campaign.recurring = false means contact can receive the same Trigger campaign only once, & recurring = true means contact can receive the same Trigger campaign several times
     * 
     * @var ?bool $recurring
     */
	#[\JMS\Serializer\Annotation\SerializedName('recurring')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $recurring = null;
    
    /**
     * Email defined as the "Reply to" of the campaign
     * 
     * @var string $replyTo
     */
	#[\JMS\Serializer\Annotation\SerializedName('replyTo')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $replyTo;
    
    /**
     * Total number of non-delivered campaigns for a particular campaign id.
     * 
     * @var ?int $returnBounce
     */
	#[\JMS\Serializer\Annotation\SerializedName('returnBounce')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $returnBounce = null;
    
    /**
     * UTC date-time on which campaign is scheduled (YYYY-MM-DDTHH:mm:ss.SSSZ)
     * 
     * @var ?string $scheduledAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('scheduledAt')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $scheduledAt = null;
    
    /**
     * It is true if you have chosen to send your campaign at best time, otherwise it is false
     * 
     * @var ?bool $sendAtBestTime
     */
	#[\JMS\Serializer\Annotation\SerializedName('sendAtBestTime')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $sendAtBestTime = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('sender')]
    #[\JMS\Serializer\Annotation\Type('test\BREVO\Models\Shared\GetEmailCampaignSender')]
    public GetEmailCampaignSender $sender;
    
    /**
     * Sent UTC date-time of the campaign (YYYY-MM-DDTHH:mm:ss.SSSZ). Only available if 'status' of the campaign is 'sent'
     * 
     * @var ?string $sentDate
     */
	#[\JMS\Serializer\Annotation\SerializedName('sentDate')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sentDate = null;
    
    /**
     * Link to share the campaign on social medias
     * 
     * @var ?string $shareLink
     */
	#[\JMS\Serializer\Annotation\SerializedName('shareLink')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $shareLink = null;
    
    /**
     * The size of your ab-test groups. Only available if `abTesting` flag of the campaign is `true`
     * 
     * @var ?int $splitRule
     */
	#[\JMS\Serializer\Annotation\SerializedName('splitRule')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $splitRule = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('statistics')]
    #[\JMS\Serializer\Annotation\Type('test\BREVO\Models\Shared\GetEmailCampaignStatistics')]
    public GetEmailCampaignStatistics $statistics;
    
    /**
     * Status of the campaign
     * 
     * @var \test\BREVO\Models\Shared\GetEmailCampaignStatus $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<test\BREVO\Models\Shared\GetEmailCampaignStatus>')]
    public GetEmailCampaignStatus $status;
    
    /**
     * Subject of the campaign. Only available if `abTesting` flag of the campaign is `false`
     * 
     * @var ?string $subject
     */
	#[\JMS\Serializer\Annotation\SerializedName('subject')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $subject = null;
    
    /**
     * Subject A of the ab-test campaign. Only available if `abTesting` flag of the campaign is `true`
     * 
     * @var ?string $subjectA
     */
	#[\JMS\Serializer\Annotation\SerializedName('subjectA')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $subjectA = null;
    
    /**
     * Subject B of the ab-test campaign. Only available if `abTesting` flag of the campaign is `true`
     * 
     * @var ?string $subjectB
     */
	#[\JMS\Serializer\Annotation\SerializedName('subjectB')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $subjectB = null;
    
    /**
     * Tag of the campaign
     * 
     * @var ?string $tag
     */
	#[\JMS\Serializer\Annotation\SerializedName('tag')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tag = null;
    
    /**
     * Retrieved the status of test email sending. (true=Test email has been sent  false=Test email has not been sent)
     * 
     * @var bool $testSent
     */
	#[\JMS\Serializer\Annotation\SerializedName('testSent')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $testSent;
    
    /**
     * Customisation of the "to" field of the campaign
     * 
     * @var ?string $toField
     */
	#[\JMS\Serializer\Annotation\SerializedName('toField')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $toField = null;
    
    /**
     * Type of campaign
     * 
     * @var \test\BREVO\Models\Shared\GetEmailCampaignType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<test\BREVO\Models\Shared\GetEmailCampaignType>')]
    public GetEmailCampaignType $type;
    
    /**
     * Criteria for the winning version. Only available if `abTesting` flag of the campaign is `true`
     * 
     * @var ?string $winnerCriteria
     */
	#[\JMS\Serializer\Annotation\SerializedName('winnerCriteria')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $winnerCriteria = null;
    
    /**
     * The duration of the test in hours at the end of which the winning version will be sent. Only available if `abTesting` flag of the campaign is `true`
     * 
     * @var ?int $winnerDelay
     */
	#[\JMS\Serializer\Annotation\SerializedName('winnerDelay')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $winnerDelay = null;
    
	public function __construct()
	{
		$this->abTesting = null;
		$this->createdAt = "";
		$this->footer = "";
		$this->header = "";
		$this->htmlContent = "";
		$this->id = 0;
		$this->inlineImageActivation = null;
		$this->mirrorActive = null;
		$this->modifiedAt = "";
		$this->name = "";
		$this->previewText = null;
		$this->recipients = new \test\BREVO\Models\Shared\GetEmailCampaignRecipients();
		$this->recurring = null;
		$this->replyTo = "";
		$this->returnBounce = null;
		$this->scheduledAt = null;
		$this->sendAtBestTime = null;
		$this->sender = new \test\BREVO\Models\Shared\GetEmailCampaignSender();
		$this->sentDate = null;
		$this->shareLink = null;
		$this->splitRule = null;
		$this->statistics = new \test\BREVO\Models\Shared\GetEmailCampaignStatistics();
		$this->status = \test\BREVO\Models\Shared\GetEmailCampaignStatus::Draft;
		$this->subject = null;
		$this->subjectA = null;
		$this->subjectB = null;
		$this->tag = null;
		$this->testSent = false;
		$this->toField = null;
		$this->type = \test\BREVO\Models\Shared\GetEmailCampaignType::Classic;
		$this->winnerCriteria = null;
		$this->winnerDelay = null;
	}
}
