<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * GetExtendedContactDetailsAttributes - Set of attributes of the contact
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class GetExtendedContactDetailsAttributes
{
	public function __construct()
	{
	}
}
