<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/** Type of campaign */
enum GetEmailCampaignsCampaignsType: string
{
    case Classic = 'classic';
    case Trigger = 'trigger';
}
