<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * GetEmailCampaignsCampaignsStatisticsGlobalStats - Overall statistics of the campaign
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class GetEmailCampaignsCampaignsStatisticsGlobalStats
{
    /**
     * Number of total clicks for the campaign
     * 
     * @var int $clickers
     */
	#[\JMS\Serializer\Annotation\SerializedName('clickers')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $clickers;
    
    /**
     * Number of complaints (Spam reports) for the campaign
     * 
     * @var int $complaints
     */
	#[\JMS\Serializer\Annotation\SerializedName('complaints')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $complaints;
    
    /**
     * Number of deferred emails for the campaign
     * 
     * @var ?int $deferred
     */
	#[\JMS\Serializer\Annotation\SerializedName('deferred')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $deferred = null;
    
    /**
     * Number of delivered emails for the campaign
     * 
     * @var int $delivered
     */
	#[\JMS\Serializer\Annotation\SerializedName('delivered')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $delivered;
    
    /**
     * Rate of recipients without any privacy protection option enabled in their email client, applied to all delivered emails
     * 
     * @var ?int $estimatedViews
     */
	#[\JMS\Serializer\Annotation\SerializedName('estimatedViews')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $estimatedViews = null;
    
    /**
     * Number of harbounce for the campaign
     * 
     * @var int $hardBounces
     */
	#[\JMS\Serializer\Annotation\SerializedName('hardBounces')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $hardBounces;
    
    /**
     * List Id of email campaign (only in case of get email campaign(s)(not for global stats))
     * 
     * @var ?int $listId
     */
	#[\JMS\Serializer\Annotation\SerializedName('listId')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $listId = null;
    
    /**
     * Total number of non-delivered campaigns for a particular campaign id.
     * 
     * @var ?int $returnBounce
     */
	#[\JMS\Serializer\Annotation\SerializedName('returnBounce')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $returnBounce = null;
    
    /**
     * Number of sent emails for the campaign
     * 
     * @var int $sent
     */
	#[\JMS\Serializer\Annotation\SerializedName('sent')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $sent;
    
    /**
     * Number of softbounce for the campaign
     * 
     * @var int $softBounces
     */
	#[\JMS\Serializer\Annotation\SerializedName('softBounces')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $softBounces;
    
    /**
     * Recipients without any privacy protection option enabled in their email client
     * 
     * @var int $trackableViews
     */
	#[\JMS\Serializer\Annotation\SerializedName('trackableViews')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $trackableViews;
    
    /**
     * Rate of recipients without any privacy protection option enabled in their email client
     * 
     * @var ?float $trackableViewsRate
     */
	#[\JMS\Serializer\Annotation\SerializedName('trackableViewsRate')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $trackableViewsRate = null;
    
    /**
     * Number of unique clicks for the campaign
     * 
     * @var int $uniqueClicks
     */
	#[\JMS\Serializer\Annotation\SerializedName('uniqueClicks')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $uniqueClicks;
    
    /**
     * Number of unique openings for the campaign
     * 
     * @var int $uniqueViews
     */
	#[\JMS\Serializer\Annotation\SerializedName('uniqueViews')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $uniqueViews;
    
    /**
     * Number of unsubscription for the campaign
     * 
     * @var int $unsubscriptions
     */
	#[\JMS\Serializer\Annotation\SerializedName('unsubscriptions')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $unsubscriptions;
    
    /**
     * Number of openings for the campaign
     * 
     * @var int $viewed
     */
	#[\JMS\Serializer\Annotation\SerializedName('viewed')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $viewed;
    
	public function __construct()
	{
		$this->clickers = 0;
		$this->complaints = 0;
		$this->deferred = null;
		$this->delivered = 0;
		$this->estimatedViews = null;
		$this->hardBounces = 0;
		$this->listId = null;
		$this->returnBounce = null;
		$this->sent = 0;
		$this->softBounces = 0;
		$this->trackableViews = 0;
		$this->trackableViewsRate = null;
		$this->uniqueClicks = 0;
		$this->uniqueViews = 0;
		$this->unsubscriptions = 0;
		$this->viewed = 0;
	}
}
