<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * GetExtendedContactDetailsStatistics - Campaign statistics of the contact
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class GetExtendedContactDetailsStatistics
{
    /**
     * Listing of the clicks generated by the contact
     * 
     * @var ?array<\test\BREVO\Models\Shared\GetExtendedContactDetailsClicked> $clicked
     */
	#[\JMS\Serializer\Annotation\SerializedName('clicked')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\GetExtendedContactDetailsClicked>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $clicked = null;
    
    /**
     * Listing of the complaints generated by the contact
     * 
     * @var ?array<\test\BREVO\Models\Shared\GetExtendedContactDetailsComplaints> $complaints
     */
	#[\JMS\Serializer\Annotation\SerializedName('complaints')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\GetExtendedContactDetailsComplaints>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $complaints = null;
    
    /**
     * Listing of the delivered campaign for the contact
     * 
     * @var ?array<\test\BREVO\Models\Shared\GetExtendedContactDetailsDelivered> $delivered
     */
	#[\JMS\Serializer\Annotation\SerializedName('delivered')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\GetExtendedContactDetailsDelivered>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $delivered = null;
    
    /**
     * Listing of the hardbounes generated by the contact
     * 
     * @var ?array<\test\BREVO\Models\Shared\GetExtendedContactDetailsHardBounces> $hardBounces
     */
	#[\JMS\Serializer\Annotation\SerializedName('hardBounces')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\GetExtendedContactDetailsHardBounces>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $hardBounces = null;
    
    /**
     * Listing of the sent campaign for the contact
     * 
     * @var ?array<\test\BREVO\Models\Shared\GetExtendedContactDetailsMessagesSent> $messagesSent
     */
	#[\JMS\Serializer\Annotation\SerializedName('messagesSent')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\GetExtendedContactDetailsMessagesSent>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $messagesSent = null;
    
    /**
     * Listing of the openings generated by the contact
     * 
     * @var ?array<\test\BREVO\Models\Shared\GetExtendedContactDetailsOpened> $opened
     */
	#[\JMS\Serializer\Annotation\SerializedName('opened')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\GetExtendedContactDetailsOpened>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $opened = null;
    
    /**
     * Listing of the softbounes generated by the contact
     * 
     * @var ?array<\test\BREVO\Models\Shared\GetExtendedContactDetailsSoftBounces> $softBounces
     */
	#[\JMS\Serializer\Annotation\SerializedName('softBounces')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\GetExtendedContactDetailsSoftBounces>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $softBounces = null;
    
    /**
     * Listing of the transactional attributes for the contact
     * 
     * @var ?array<\test\BREVO\Models\Shared\GetExtendedContactDetailsTransacAttributes> $transacAttributes
     */
	#[\JMS\Serializer\Annotation\SerializedName('transacAttributes')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\GetExtendedContactDetailsTransacAttributes>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $transacAttributes = null;
    
    /**
     * Listing of the unsubscription for the contact
     * 
     * @var ?\test\BREVO\Models\Shared\GetExtendedContactDetailsUnsubscriptions $unsubscriptions
     */
	#[\JMS\Serializer\Annotation\SerializedName('unsubscriptions')]
    #[\JMS\Serializer\Annotation\Type('test\BREVO\Models\Shared\GetExtendedContactDetailsUnsubscriptions')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?GetExtendedContactDetailsUnsubscriptions $unsubscriptions = null;
    
	public function __construct()
	{
		$this->clicked = null;
		$this->complaints = null;
		$this->delivered = null;
		$this->hardBounces = null;
		$this->messagesSent = null;
		$this->opened = null;
		$this->softBounces = null;
		$this->transacAttributes = null;
		$this->unsubscriptions = null;
	}
}
