<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * GetEmailEventReport - Email events report informations
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class GetEmailEventReport
{
    /**
     * $events
     * 
     * @var ?array<\test\BREVO\Models\Shared\GetEmailEventReportEvents> $events
     */
	#[\JMS\Serializer\Annotation\SerializedName('events')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\GetEmailEventReportEvents>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $events = null;
    
	public function __construct()
	{
		$this->events = null;
	}
}
