<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * GetEmailCampaignStatisticsLinksStats - Statistics about the number of clicks for the links
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class GetEmailCampaignStatisticsLinksStats
{
	public function __construct()
	{
	}
}
