<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class GetExtendedContactDetailsStatisticsTransacAttributes
{
	public function __construct()
	{
	}
}
