<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class GetInboundEmailEventsByUuidLogs
{
    /**
     * Date of the event
     * 
     * @var ?\DateTime $date
     */
	#[\JMS\Serializer\Annotation\SerializedName('date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $date = null;
    
    /**
     * Type of the event
     * 
     * @var ?\test\BREVO\Models\Shared\GetInboundEmailEventsByUuidType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<test\BREVO\Models\Shared\GetInboundEmailEventsByUuidType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?GetInboundEmailEventsByUuidType $type = null;
    
	public function __construct()
	{
		$this->date = null;
		$this->type = null;
	}
}
