<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class GetInboundEmailEventsEvents
{
    /**
     * Date when email was received on SMTP relay
     * 
     * @var \DateTime $date
     */
	#[\JMS\Serializer\Annotation\SerializedName('date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $date;
    
    /**
     * Recipient’s email address
     * 
     * @var string $recipient
     */
	#[\JMS\Serializer\Annotation\SerializedName('recipient')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $recipient;
    
    /**
     * Sender’s email address
     * 
     * @var string $sender
     */
	#[\JMS\Serializer\Annotation\SerializedName('sender')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $sender;
    
    /**
     * UUID that can be used to fetch additional data
     * 
     * @var string $uuid
     */
	#[\JMS\Serializer\Annotation\SerializedName('uuid')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $uuid;
    
	public function __construct()
	{
		$this->date = new \DateTime();
		$this->recipient = "";
		$this->sender = "";
		$this->uuid = "";
	}
}
