<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * GetInvitedUsersList - list of all your users
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class GetInvitedUsersList
{
    /**
     * Get invited users list
     * 
     * @var ?array<\test\BREVO\Models\Shared\GetInvitedUsersListUsers> $users
     */
	#[\JMS\Serializer\Annotation\SerializedName('users')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\GetInvitedUsersListUsers>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $users = null;
    
	public function __construct()
	{
		$this->users = null;
	}
}
