<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class GetLists
{
    /**
     * Number of lists in your account
     * 
     * @var ?int $count
     */
	#[\JMS\Serializer\Annotation\SerializedName('count')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $count = null;
    
    /**
     * Listing of all the lists available in your account
     * 
     * @var ?array<\test\BREVO\Models\Shared\GetListsLists> $lists
     */
	#[\JMS\Serializer\Annotation\SerializedName('lists')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\GetListsLists>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $lists = null;
    
	public function __construct()
	{
		$this->count = null;
		$this->lists = null;
	}
}
