<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * GetProcess - process informations
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class GetProcess
{
    /**
     * URL on which send export the of contacts once the process is completed
     * 
     * @var ?string $exportUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('export_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $exportUrl = null;
    
    /**
     * Id of the process
     * 
     * @var int $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
    /**
     * Process name
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * Status of the process
     * 
     * @var \test\BREVO\Models\Shared\GetProcessStatus $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<test\BREVO\Models\Shared\GetProcessStatus>')]
    public GetProcessStatus $status;
    
	public function __construct()
	{
		$this->exportUrl = null;
		$this->id = 0;
		$this->name = "";
		$this->status = \test\BREVO\Models\Shared\GetProcessStatus::Queued;
	}
}
