<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class GetReports
{
    /**
     * $reports
     * 
     * @var ?array<\test\BREVO\Models\Shared\Reports> $reports
     */
	#[\JMS\Serializer\Annotation\SerializedName('reports')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\Reports>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $reports = null;
    
	public function __construct()
	{
		$this->reports = null;
	}
}
