<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class GetScheduledEmailByMessageId
{
    /**
     * Datetime on which the email was scheduled
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('createdAt')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
    /**
     * Datetime for which the email was scheduled
     * 
     * @var \DateTime $scheduledAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('scheduledAt')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $scheduledAt;
    
    /**
     * Current status of the scheduled email
     * 
     * @var \test\BREVO\Models\Shared\GetScheduledEmailByMessageIdStatus $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<test\BREVO\Models\Shared\GetScheduledEmailByMessageIdStatus>')]
    public GetScheduledEmailByMessageIdStatus $status;
    
	public function __construct()
	{
		$this->createdAt = new \DateTime();
		$this->scheduledAt = new \DateTime();
		$this->status = \test\BREVO\Models\Shared\GetScheduledEmailByMessageIdStatus::InProgress;
	}
}
