<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class GetSendersListSenders
{
    /**
     * Status of sender (true=activated, false=deactivated)
     * 
     * @var bool $active
     */
	#[\JMS\Serializer\Annotation\SerializedName('active')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $active;
    
    /**
     * From Email associated to the sender
     * 
     * @var string $email
     */
	#[\JMS\Serializer\Annotation\SerializedName('email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $email;
    
    /**
     * Id of the sender
     * 
     * @var int $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
    /**
     * List of dedicated IP(s) available in the account. This data is displayed only for dedicated IPs
     * 
     * @var ?array<\test\BREVO\Models\Shared\GetSendersListSendersIps> $ips
     */
	#[\JMS\Serializer\Annotation\SerializedName('ips')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\GetSendersListSendersIps>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $ips = null;
    
    /**
     * From Name associated to the sender
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	public function __construct()
	{
		$this->active = false;
		$this->email = "";
		$this->id = 0;
		$this->ips = null;
		$this->name = "";
	}
}
