<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class GetScheduledEmailByBatchId
{
    /**
     * $batches
     * 
     * @var ?array<\test\BREVO\Models\Shared\GetScheduledEmailByBatchIdBatches> $batches
     */
	#[\JMS\Serializer\Annotation\SerializedName('batches')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\GetScheduledEmailByBatchIdBatches>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $batches = null;
    
    /**
     * Total number of batches
     * 
     * @var ?int $count
     */
	#[\JMS\Serializer\Annotation\SerializedName('count')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $count = null;
    
	public function __construct()
	{
		$this->batches = null;
		$this->count = null;
	}
}
