<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * GetSharedTemplateUrl - Shared template URL information
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class GetSharedTemplateUrl
{
    /**
     * A unique URL for the email campaign or transactional template. This URL can be shared with other Brevo users.
     * 
     * @var string $sharedUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('sharedUrl')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $sharedUrl;
    
	public function __construct()
	{
		$this->sharedUrl = "";
	}
}
