<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class GetSegments
{
    /**
     * Number of Segments in your account
     * 
     * @var ?int $count
     */
	#[\JMS\Serializer\Annotation\SerializedName('count')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $count = null;
    
    /**
     * Listing of all the segments available in your account
     * 
     * @var ?array<\test\BREVO\Models\Shared\Segments> $segments
     */
	#[\JMS\Serializer\Annotation\SerializedName('segments')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\Segments>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $segments = null;
    
	public function __construct()
	{
		$this->count = null;
		$this->segments = null;
	}
}
