<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * GetTransacBlockedContacts - List of blocked or unsubscribed transactional contacts
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class GetTransacBlockedContacts
{
    /**
     * $contacts
     * 
     * @var ?array<\test\BREVO\Models\Shared\GetTransacBlockedContactsContacts> $contacts
     */
	#[\JMS\Serializer\Annotation\SerializedName('contacts')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\GetTransacBlockedContactsContacts>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $contacts = null;
    
    /**
     * Count of blocked or unsubscribed contact
     * 
     * @var ?int $count
     */
	#[\JMS\Serializer\Annotation\SerializedName('count')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $count = null;
    
	public function __construct()
	{
		$this->contacts = null;
		$this->count = null;
	}
}
