<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/** Type of webhook (marketing or transactional) */
enum GetWebhooksWebhooksType: string
{
    case Marketing = 'marketing';
    case Transactional = 'transactional';
}
