<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/** Language of the child account */
enum Language: string
{
    case Fr = 'fr';
    case Es = 'es';
    case Pt = 'pt';
    case It = 'it';
    case De = 'de';
    case En = 'en';
}
