<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * MasterDetailsResponsePlanInfo - Plan details
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class MasterDetailsResponsePlanInfo
{
    /**
     * Plan currency
     * 
     * @var ?string $currencyCode
     */
	#[\JMS\Serializer\Annotation\SerializedName('currencyCode')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $currencyCode = null;
    
    /**
     * List of provided features in the plan
     * 
     * @var ?array<\test\BREVO\Models\Shared\MasterDetailsResponsePlanInfoFeatures> $features
     */
	#[\JMS\Serializer\Annotation\SerializedName('features')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\MasterDetailsResponsePlanInfoFeatures>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $features = null;
    
    /**
     * Timestamp of next billing date
     * 
     * @var ?int $nextBillingAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('nextBillingAt')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $nextBillingAt = null;
    
    /**
     * Plan period type
     * 
     * @var ?\test\BREVO\Models\Shared\MasterDetailsResponsePlanInfoPlanPeriod $planPeriod
     */
	#[\JMS\Serializer\Annotation\SerializedName('planPeriod')]
    #[\JMS\Serializer\Annotation\Type('enum<test\BREVO\Models\Shared\MasterDetailsResponsePlanInfoPlanPeriod>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?MasterDetailsResponsePlanInfoPlanPeriod $planPeriod = null;
    
    /**
     * Plan amount
     * 
     * @var ?float $price
     */
	#[\JMS\Serializer\Annotation\SerializedName('price')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $price = null;
    
    /**
     * Number of sub-accounts
     * 
     * @var ?int $subAccounts
     */
	#[\JMS\Serializer\Annotation\SerializedName('subAccounts')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $subAccounts = null;
    
	public function __construct()
	{
		$this->currencyCode = null;
		$this->features = null;
		$this->nextBillingAt = null;
		$this->planPeriod = null;
		$this->price = null;
		$this->subAccounts = null;
	}
}
