<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * OrderProducts - Details for the Products in an order.
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class OrderProducts
{
    /**
     * The price of a unit of product
     * 
     * @var float $price
     */
	#[\JMS\Serializer\Annotation\SerializedName('price')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $price;
    
    /**
     * ID of the product.
     * 
     * @var string $productId
     */
	#[\JMS\Serializer\Annotation\SerializedName('productId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $productId;
    
    /**
     * How many pieces of the product the visitor has added to the cart.
     * 
     * @var float $quantity
     */
	#[\JMS\Serializer\Annotation\SerializedName('quantity')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $quantity;
    
    /**
     * Product ID of the red color shirts.
     * 
     * @var ?string $variantId
     */
	#[\JMS\Serializer\Annotation\SerializedName('variantId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $variantId = null;
    
	public function __construct()
	{
		$this->price = 0;
		$this->productId = "";
		$this->quantity = 0;
		$this->variantId = null;
	}
}
