<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class Otp
{
    /**
     * 6 digit OTP received on email
     * 
     * @var int $otp
     */
	#[\JMS\Serializer\Annotation\SerializedName('otp')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $otp;
    
	public function __construct()
	{
		$this->otp = 0;
	}
}
