<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * Pipeline - List of stages
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class Pipeline
{
    /**
     * Pipeline id
     * 
     * @var ?string $pipeline
     */
	#[\JMS\Serializer\Annotation\SerializedName('pipeline')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $pipeline = null;
    
    /**
     * Pipeline name
     * 
     * @var ?string $pipelineName
     */
	#[\JMS\Serializer\Annotation\SerializedName('pipeline_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $pipelineName = null;
    
    /**
     * List of stages
     * 
     * @var ?array<\test\BREVO\Models\Shared\PipelineStage> $stages
     */
	#[\JMS\Serializer\Annotation\SerializedName('stages')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\PipelineStage>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $stages = null;
    
	public function __construct()
	{
		$this->pipeline = null;
		$this->pipelineName = null;
		$this->stages = null;
	}
}
