<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * PostSendFailed - Test email could not be sent to the following email addresses
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class PostSendFailed
{
    /**
     * $blackListedEmails
     * 
     * @var ?array<string> $blackListedEmails
     */
	#[\JMS\Serializer\Annotation\SerializedName('blackListedEmails')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $blackListedEmails = null;
    
    /**
     * Response code
     * 
     * @var string $code
     */
	#[\JMS\Serializer\Annotation\SerializedName('code')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $code;
    
    /**
     * Response message
     * 
     * @var string $message
     */
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $message;
    
    /**
     * $unexistingEmails
     * 
     * @var ?array<string> $unexistingEmails
     */
	#[\JMS\Serializer\Annotation\SerializedName('unexistingEmails')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $unexistingEmails = null;
    
    /**
     * $withoutListEmails
     * 
     * @var ?array<string> $withoutListEmails
     */
	#[\JMS\Serializer\Annotation\SerializedName('withoutListEmails')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $withoutListEmails = null;
    
	public function __construct()
	{
		$this->blackListedEmails = null;
		$this->code = "";
		$this->message = "";
		$this->unexistingEmails = null;
		$this->withoutListEmails = null;
	}
}
