<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class RemainingCreditModel
{
    /**
     * Credits remaining for child account
     * 
     * @var \test\BREVO\Models\Shared\RemainingCreditModelChild $child
     */
	#[\JMS\Serializer\Annotation\SerializedName('child')]
    #[\JMS\Serializer\Annotation\Type('test\BREVO\Models\Shared\RemainingCreditModelChild')]
    public RemainingCreditModelChild $child;
    
	#[\JMS\Serializer\Annotation\SerializedName('reseller')]
    #[\JMS\Serializer\Annotation\Type('test\BREVO\Models\Shared\RemainingCreditModelReseller')]
    public RemainingCreditModelReseller $reseller;
    
	public function __construct()
	{
		$this->child = new \test\BREVO\Models\Shared\RemainingCreditModelChild();
		$this->reseller = new \test\BREVO\Models\Shared\RemainingCreditModelReseller();
	}
}
