<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class RemainingCreditModel
{
    /**
     * Credits remaining for child account
     * 
     * @var \test\BREVO\Models\Shared\Child $child
     */
	#[\JMS\Serializer\Annotation\SerializedName('child')]
    #[\JMS\Serializer\Annotation\Type('test\BREVO\Models\Shared\Child')]
    public Child $child;
    
	#[\JMS\Serializer\Annotation\SerializedName('reseller')]
    #[\JMS\Serializer\Annotation\Type('test\BREVO\Models\Shared\Reseller')]
    public Reseller $reseller;
    
	public function __construct()
	{
		$this->child = new \test\BREVO\Models\Shared\Child();
		$this->reseller = new \test\BREVO\Models\Shared\Reseller();
	}
}
