<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * **Mandatory if neither actionForEmailCampaigns nor actionForSmsCampaigns is passed.** This will export the contacts on the basis of provided action applied on contacts as per the list id.
 * 
 * * **allContacts** - Fetch the list of all contacts for a particular list.
 * * **subscribed & unsubscribed** - Fetch the list of subscribed / unsubscribed (blacklisted via any means) contacts for a particular list.
 * * **unsubscribedPerList** - Fetch the list of contacts that are unsubscribed from a particular list only.
 * 
 */
enum RequestContactExportCustomContactFilterActionForContacts: string
{
    case AllContacts = 'allContacts';
    case Subscribed = 'subscribed';
    case Unsubscribed = 'unsubscribed';
    case UnsubscribedPerList = 'unsubscribedPerList';
}
