<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class ScheduleSmtpEmail
{
    /**
     * Batch ID of the batch transactional email scheduled
     * 
     * @var ?string $batchId
     */
	#[\JMS\Serializer\Annotation\SerializedName('batchId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $batchId = null;
    
    /**
     * Message ID of the transactional email scheduled
     * 
     * @var ?string $messageId
     */
	#[\JMS\Serializer\Annotation\SerializedName('messageId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $messageId = null;
    
    /**
     * $messageIds
     * 
     * @var ?array<string> $messageIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('messageIds')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $messageIds = null;
    
	public function __construct()
	{
		$this->batchId = null;
		$this->messageId = null;
		$this->messageIds = null;
	}
}
