<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class SendWhatsappMessageText
{
    /**
     * List of phone numbers of the contacts
     * 
     * @var array<string> $contactNumbers
     */
	#[\JMS\Serializer\Annotation\SerializedName('contactNumbers')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $contactNumbers;
    
    /**
     * WhatsApp Number with country code. Example, 85264318721
     * 
     * @var string $senderNumber
     */
	#[\JMS\Serializer\Annotation\SerializedName('senderNumber')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $senderNumber;
    
    /**
     * Text to be sent as message body (will be overridden if templateId is passed in the same request)
     * 
     * @var string $text
     */
	#[\JMS\Serializer\Annotation\SerializedName('text')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $text;
    
	public function __construct()
	{
		$this->contactNumbers = [];
		$this->senderNumber = "";
		$this->text = "";
	}
}
