<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * SendReport - Values for send a report
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class SendReport
{
    /**
     * Custom attributes for the report email.
     * 
     * @var \test\BREVO\Models\Shared\SendReportEmail $email
     */
	#[\JMS\Serializer\Annotation\SerializedName('email')]
    #[\JMS\Serializer\Annotation\Type('test\BREVO\Models\Shared\SendReportEmail')]
    public SendReportEmail $email;
    
    /**
     * Language of email content for campaign report sending.
     * 
     * @var ?\test\BREVO\Models\Shared\SendReportLanguage $language
     */
	#[\JMS\Serializer\Annotation\SerializedName('language')]
    #[\JMS\Serializer\Annotation\Type('enum<test\BREVO\Models\Shared\SendReportLanguage>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?SendReportLanguage $language = null;
    
	public function __construct()
	{
		$this->email = new \test\BREVO\Models\Shared\SendReportEmail();
		$this->language = null;
	}
}
