<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class SendReport
{
    /**
     * Custom attributes for the report email.
     * 
     * @var \test\BREVO\Models\Shared\Email $email
     */
	#[\JMS\Serializer\Annotation\SerializedName('email')]
    #[\JMS\Serializer\Annotation\Type('test\BREVO\Models\Shared\Email')]
    public Email $email;
    
    /**
     * Language of email content for campaign report sending.
     * 
     * @var ?\test\BREVO\Models\Shared\SendReportLanguage $language
     */
	#[\JMS\Serializer\Annotation\SerializedName('language')]
    #[\JMS\Serializer\Annotation\Type('enum<test\BREVO\Models\Shared\SendReportLanguage>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?SendReportLanguage $language = null;
    
	public function __construct()
	{
		$this->email = new \test\BREVO\Models\Shared\Email();
		$this->language = null;
	}
}
