<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class SendWhatsappMessageTemplate
{
    /**
     * List of phone numbers of the contacts
     * 
     * @var array<string> $contactNumbers
     */
	#[\JMS\Serializer\Annotation\SerializedName('contactNumbers')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $contactNumbers;
    
    /**
     * WhatsApp Number with country code. Example, 85264318721
     * 
     * @var string $senderNumber
     */
	#[\JMS\Serializer\Annotation\SerializedName('senderNumber')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $senderNumber;
    
    /**
     * ID of the template to send
     * 
     * @var int $templateId
     */
	#[\JMS\Serializer\Annotation\SerializedName('templateId')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $templateId;
    
	public function __construct()
	{
		$this->contactNumbers = [];
		$this->senderNumber = "";
		$this->templateId = 0;
	}
}
