<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * SubAccountUpdatePlanRequest - Details of the plan to be changed
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class SubAccountUpdatePlanRequest
{
    /**
     * Credit details to update
     * 
     * @var ?\test\BREVO\Models\Shared\SubAccountUpdatePlanRequestCredits $credits
     */
	#[\JMS\Serializer\Annotation\SerializedName('credits')]
    #[\JMS\Serializer\Annotation\Type('test\BREVO\Models\Shared\SubAccountUpdatePlanRequestCredits')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?SubAccountUpdatePlanRequestCredits $credits = null;
    
    /**
     * Features details to update
     * 
     * @var ?\test\BREVO\Models\Shared\SubAccountUpdatePlanRequestFeatures $features
     */
	#[\JMS\Serializer\Annotation\SerializedName('features')]
    #[\JMS\Serializer\Annotation\Type('test\BREVO\Models\Shared\SubAccountUpdatePlanRequestFeatures')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?SubAccountUpdatePlanRequestFeatures $features = null;
    
	public function __construct()
	{
		$this->credits = null;
		$this->features = null;
	}
}
