<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * SubAccountDetailsResponseCredits - Credits quota and remaining credits on the sub-account
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class SubAccountDetailsResponseCredits
{
    /**
     * Email credits remaining on the sub-account
     * 
     * @var ?\test\BREVO\Models\Shared\Emails $emails
     */
	#[\JMS\Serializer\Annotation\SerializedName('emails')]
    #[\JMS\Serializer\Annotation\Type('test\BREVO\Models\Shared\Emails')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Emails $emails = null;
    
    /**
     * SMS credits remaining on the sub-account
     * 
     * @var ?int $sms
     */
	#[\JMS\Serializer\Annotation\SerializedName('sms')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $sms = null;
    
	public function __construct()
	{
		$this->emails = null;
		$this->sms = null;
	}
}
