<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class Unsubscriptions
{
    /**
     * Contact has been unsubscribed from the administrator
     * 
     * @var array<\test\BREVO\Models\Shared\AdminUnsubscription> $adminUnsubscription
     */
	#[\JMS\Serializer\Annotation\SerializedName('adminUnsubscription')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\AdminUnsubscription>')]
    public array $adminUnsubscription;
    
    /**
     * Contact has unsubscribed via the unsubscription link in the email
     * 
     * @var array<\test\BREVO\Models\Shared\UserUnsubscription> $userUnsubscription
     */
	#[\JMS\Serializer\Annotation\SerializedName('userUnsubscription')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\UserUnsubscription>')]
    public array $userUnsubscription;
    
	public function __construct()
	{
		$this->adminUnsubscription = [];
		$this->userUnsubscription = [];
	}
}
