<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


class UpdateAttribute
{
    /**
     * List of the values and labels that the attribute can take. **Use only if the attribute's category is "category"**. For example,
     * 
     * **[{"value":1, "label":"male"}, {"value":2, "label":"female"}]**
     * 
     * 
     * @var ?array<\test\BREVO\Models\Shared\UpdateAttributeEnumeration> $enumeration
     */
	#[\JMS\Serializer\Annotation\SerializedName('enumeration')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\UpdateAttributeEnumeration>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $enumeration = null;
    
    /**
     * Value of the attribute to update. **Use only if the attribute's category is 'calculated' or 'global'**
     * 
     * 
     * 
     * @var ?string $value
     */
	#[\JMS\Serializer\Annotation\SerializedName('value')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $value = null;
    
	public function __construct()
	{
		$this->enumeration = null;
		$this->value = null;
	}
}
