<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * UpdateSender - sender's name
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class UpdateSender
{
    /**
     * From Email to update the sender
     * 
     * @var ?string $email
     */
	#[\JMS\Serializer\Annotation\SerializedName('email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $email = null;
    
    /**
     * **Only in case of dedicated IP**. IPs to associate to the sender. If passed, will replace all the existing IPs.
     * 
     * 
     * 
     * @var ?array<\test\BREVO\Models\Shared\UpdateSenderIps> $ips
     */
	#[\JMS\Serializer\Annotation\SerializedName('ips')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\UpdateSenderIps>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $ips = null;
    
    /**
     * From Name to update the sender
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
	public function __construct()
	{
		$this->email = null;
		$this->ips = null;
		$this->name = null;
	}
}
