<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * Note:- **replicateTemplate** status will be available **only for template type campaigns.**
 * 
 * 
 */
enum UpdateCampaignStatusStatus: string
{
    case Suspended = 'suspended';
    case Archive = 'archive';
    case Darchive = 'darchive';
    case Sent = 'sent';
    case Queued = 'queued';
    case Replicate = 'replicate';
    case ReplicateTemplate = 'replicateTemplate';
    case Draft = 'draft';
}
