<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * UpdateEmailCampaignRecipients - Segment ids and List ids to include/exclude from campaign
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class UpdateEmailCampaignRecipients
{
    /**
     * List ids which have to be excluded from a campaign
     * 
     * @var ?array<int> $exclusionListIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('exclusionListIds')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $exclusionListIds = null;
    
    /**
     * Lists Ids to send the campaign to. **Campaign should only be updated with listIds if listIds were used to create it. REQUIRED if already not present in campaign and scheduledAt is not empty**
     * 
     * 
     * 
     * @var ?array<int> $listIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('listIds')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $listIds = null;
    
    /**
     * **Mandatory if listIds are not used. Campaign should only be updated with segmentIds if segmentIds were used to create it.** Segment ids to send the campaign to.
     * 
     * 
     * 
     * @var ?array<int> $segmentIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('segmentIds')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $segmentIds = null;
    
	public function __construct()
	{
		$this->exclusionListIds = null;
		$this->listIds = null;
		$this->segmentIds = null;
	}
}
