<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * UpdateBatchContacts - Values to update multiple contacts
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class UpdateBatchContacts
{
    /**
     * List of contacts to be updated
     * 
     * @var ?array<\test\BREVO\Models\Shared\UpdateBatchContactsContacts> $contacts
     */
	#[\JMS\Serializer\Annotation\SerializedName('contacts')]
    #[\JMS\Serializer\Annotation\Type('array<test\BREVO\Models\Shared\UpdateBatchContactsContacts>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $contacts = null;
    
	public function __construct()
	{
		$this->contacts = null;
	}
}
