<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/**
 * UpdateWhatsAppCampaign - Values to update a WhatsApp Campaign
 * 
 * @package test\BREVO\Models\Shared
 * @access public
 */
class UpdateWhatsAppCampaign
{
    /**
     * Name of the campaign
     * 
     * @var ?string $campaignName
     */
	#[\JMS\Serializer\Annotation\SerializedName('campaignName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $campaignName = null;
    
    /**
     * Status of the campaign
     * 
     * @var ?\test\BREVO\Models\Shared\UpdateWhatsAppCampaignCampaignStatus $campaignStatus
     */
	#[\JMS\Serializer\Annotation\SerializedName('campaignStatus')]
    #[\JMS\Serializer\Annotation\Type('enum<test\BREVO\Models\Shared\UpdateWhatsAppCampaignCampaignStatus>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?UpdateWhatsAppCampaignCampaignStatus $campaignStatus = null;
    
    /**
     * Segment ids and List ids to include/exclude from campaign
     * 
     * @var ?\test\BREVO\Models\Shared\UpdateWhatsAppCampaignRecipients $recipients
     */
	#[\JMS\Serializer\Annotation\SerializedName('recipients')]
    #[\JMS\Serializer\Annotation\Type('test\BREVO\Models\Shared\UpdateWhatsAppCampaignRecipients')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?UpdateWhatsAppCampaignRecipients $recipients = null;
    
    /**
     * Reschedule the sending UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ) of campaign. **Prefer to pass your timezone in date-time format for accurate result.For example: **2017-06-01T12:30:00+02:00**
     * 
     * Use this field to update the scheduledAt of any existing draft or scheduled WhatsApp campaign.
     * 
     * 
     * @var ?string $rescheduleFor
     */
	#[\JMS\Serializer\Annotation\SerializedName('rescheduleFor')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $rescheduleFor = null;
    
	public function __construct()
	{
		$this->campaignName = null;
		$this->campaignStatus = null;
		$this->recipients = null;
		$this->rescheduleFor = null;
	}
}
