<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test\BREVO\Models\Shared;


/** Criteria choosen for winning version (Open/Click) */
enum WinningCriteria: string
{
    case Open = 'Open';
    case Click = 'Click';
}
